### ISSUE TITLE
Transfer to audiojs?

### ISSUE THREAD

**Issue by dfcreative** [audiojs/audio-type#25]
Hi @hemanth!

Thanks for the robust package, we heavily depend on it in @audiojs in [audio-decode](https://github.com/audiojs/audio-decode) and upcoming [web-audio-api](https://github.com/audiojs/web-audio-api) release.
Just a humble suggestion − since you are the member of @audiojs − is there a sense to transfer the package there? We will set greenkeeper, API docs and badges for that. Also we  could take care of better detecting and resolving bugs if you have no time, for example, like here https://github.com/hemanth/is-mp3/issues/17.
Of course you will be the owner of the package.
The name perfectly fits to the naming of audio-* packages.

Cheers!

**Comment by hemanth** [comment]
Done.

**Comment by dfcreative** [comment]
Wonderful, thank you!
Do you mind also adding us as a npm-contributors?
```bash
npm owner add jamen audio-type
npm owner add dfcreative audio-type
```

**Comment by hemanth** [comment]
Done.
